### ISSUE TITLE
Todo tasks

### ISSUE THREAD

**Issue by Arvraepe** [TheTommyTwitch/pokedex-promise-v2#1]
Hi, I'm interested in contributing to the project, I'm new to open source development and know my way around NodeJS. I'd like to jump in and do some work to complete the wrapper.

Would it be possible to put some todo's on the issues list so I can start contributing?

Thanks!

**Comment by TheTommyTwitch** [comment]
I'm glad you want to contribute! I should have the main functionality done in the next day or two. I would love help with the documentation or tests. I started on the documentation in the readme to give you an idea if you want to work on that.
